# TASK_TYPE must by FREQUENCY or VOLUME
TASK_TYPE: 'FREQUENCY'


TRAINING_TRIALS: [{level: 50, n_trails: 2}, {level: 20, n_trails: 2}]
START_LEVEL: 50
MAX_REVS: 3
MAX_TRIALS: 20
MIN_LEVEL: 3
MAX_LEVEL: 60
STEP: 3

# visual parameters
TEXT_SIZE: 32


# sounds parameters
## WAVE_TYPE must by sin or white
WAVE_TYPE: 'sin'
VOLUME: 1


## Fix sound parameters
PLAY_FIX_SOUND: FALSE
GENERATE_FIX_SOUND: FALSE
FIX_TIME: 0.1
FIX_SAMPLE_RATE: 4100.0
FIX_FREQUENCY: 100000.0

DELAY: 1

## Standard sound parameters
GENERATE_STANDART_SOUND: True
S_TIME: 0.1
S_SAMPLE_RATE: 44100.0
S_FREQUENCY: 440.0

ISI: 1

RTIME: 1

JITTER_TIME: 1
